# Generated by Django 3.0.7 on 2020-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode6', '0003_auto_20200620_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='x',
            field=models.FloatField(default=0, help_text='Normal strain along x direction.', verbose_name=' ε_x'),
        ),
        migrations.AlterField(
            model_name='input',
            name='xy',
            field=models.FloatField(default=0, help_text='Shear strain.', verbose_name=' γ_xy'),
        ),
        migrations.AlterField(
            model_name='input',
            name='y',
            field=models.FloatField(default=0, help_text='Normal strain along y direction.', verbose_name=' ε_y'),
        ),
    ]
