# Generated by Django 3.0.7 on 2020-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0, verbose_name='sigma_x')),
                ('y', models.FloatField(default=0, verbose_name='sigma_y')),
                ('xy', models.FloatField(default=0, verbose_name='tau_xy')),
                ('opt', models.FloatField(default=0, verbose_name='power')),
                ('setta', models.FloatField(default=0, verbose_name='theta')),
            ],
        ),
    ]
