# Generated by Django 3.0.7 on 2020-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='opt',
        ),
        migrations.AlterField(
            model_name='input',
            name='x',
            field=models.FloatField(default=0, verbose_name='epsilon_x'),
        ),
        migrations.AlterField(
            model_name='input',
            name='xy',
            field=models.FloatField(default=0, verbose_name='gamma_xy'),
        ),
        migrations.AlterField(
            model_name='input',
            name='y',
            field=models.FloatField(default=0, verbose_name='epsilon_y'),
        ),
    ]
