# Generated by Django 3.0.7 on 2020-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode4', '0002_auto_20200620_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='unit',
            field=models.FloatField(default=-6, help_text='Please write the power of unit. ex) 2*10^(-6) => -6', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='input',
            name='setta',
            field=models.FloatField(default=0, verbose_name=' ϑ'),
        ),
        migrations.AlterField(
            model_name='input',
            name='x',
            field=models.FloatField(default=0, verbose_name=' ε_x'),
        ),
        migrations.AlterField(
            model_name='input',
            name='xy',
            field=models.FloatField(default=0, verbose_name=' γ_xy'),
        ),
        migrations.AlterField(
            model_name='input',
            name='y',
            field=models.FloatField(default=0, verbose_name=' ε_y'),
        ),
    ]
